USE boardgameDB;

DROP TABLE IF EXISTS Group;

CREATE TABLE Group (
	GroupId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    GroupName VARCHAR(50) NOT NULL,
    GroupDesc VARCHAR(500) NOT NULL
);